const {JSDOM,VirtualConsole}=require(process.env.ATLAS_JSDOM_PATH||'jsdom');
const fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'../dist/classics-atlas.html'),'utf8');
const errors=[];
function load(saved={},mobile=false){
 const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 return new JSDOM(html,{url:'https://atlas.example.test/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){
   w.structuredClone=structuredClone;w.innerWidth=mobile?390:1440;w.innerHeight=mobile?844:900;
   Object.defineProperty(w.HTMLElement.prototype,'clientWidth',{get(){return w.innerWidth;}});
   Object.defineProperty(w.HTMLElement.prototype,'clientHeight',{get(){return w.innerHeight;}});
   Object.defineProperty(w.SVGElement.prototype,'viewBox',{get(){return {baseVal:{x:0,y:0,width:w.innerWidth,height:w.innerHeight}};}});
   w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
   for(const [k,v]of Object.entries(saved))w.localStorage.setItem(k,v);
 }});
}
let dom=load(),w=dom.window,d=w.document;
const click=s=>{const e=d.querySelector(s);assert(e,'Missing '+s);e.click?e.click():e.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));};
const change=(s,value)=>{const e=d.querySelector(s);e.value=value;e.dispatchEvent(new w.Event('change',{bubbles:true}));};
const search=q=>{d.querySelector('#searchInput').value=q;d.querySelector('#searchForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));};
assert(w.ClassicsAtlas,'application initialized: '+errors.join('; '));assert.equal(w.ClassicsAtlas.catalogSize,1479);
assert.equal(d.querySelector('.map-caption'),null,'promotional headline removed, not merely hidden');
assert(!d.querySelector('#filters').hidden,'desktop filters start open');
click('#collapseFilters');
click('#mobileFilters');assert(!d.querySelector('#filters').hidden);assert(d.body.classList.contains('filters-open'));assert.equal(d.querySelector('#mobileFilters').getAttribute('aria-expanded'),'true');click('#collapseFilters');assert(d.querySelector('#filters').hidden);
assert.equal(d.querySelectorAll('.country').length,177);assert(d.querySelector('.country').getAttribute('d').length>10);
assert.equal(w.ClassicsAtlas.getResults().length,1479);assert.equal(d.querySelectorAll('.book-card').length,30);
assert.equal(d.querySelectorAll('#mapPeriod option').length,13);
// Country expansion changes presentation without changing the selected books.
click('.country[data-country="CHN"]');
const countryResults=w.ClassicsAtlas.getResults().join(',');
click('#expandCollection');assert(d.body.classList.contains('collection-expanded'));
assert.equal(d.querySelector('#expandCollection').getAttribute('aria-expanded'),'true');
assert.equal(w.ClassicsAtlas.getResults().join(','),countryResults);
click('#expandCollection');assert(!d.body.classList.contains('collection-expanded'));
assert.equal(w.ClassicsAtlas.getState().country,'CHN');
click('.book-title');
assert.deepEqual([...d.querySelectorAll('#detailContent>.notes-section>h3')].map(x=>x.textContent),['At a glance','When it began','Its place on the map','About this edition']);
const sourceNotes=d.querySelector('[data-notes="sources"]');sourceNotes.open=true;
click('#detailContent [data-rate][data-rating="3"]');assert(d.querySelector('[data-notes="sources"]').open,'rating preserves open notes');
assert.equal(d.querySelector('#detailDialog').getAttribute('aria-labelledby'),'bookNotesTitle');
const testedId=d.querySelector('#detailContent [data-status]').dataset.status;change('#detailContent [data-status]','');assert(!w.ClassicsAtlas.getShelf?.()?.[testedId]);
click('[data-close="detailDialog"]');click('#resetBtn');

const initialResults=w.ClassicsAtlas.getResults();
for(const preset of w.ATLAS_DATA.historical.presets){
 change('#mapPeriod',preset.id);
 assert.equal(d.querySelectorAll('.historical-region').length,preset.features.length);
 assert(d.querySelector('.historical-region').getAttribute('d').length>10,preset.id);
 assert.equal(w.ClassicsAtlas.getState().to,preset.year);assert.equal(w.ClassicsAtlas.getState().from,-2500);assert(d.querySelector('[data-era].active'),'historical map highlights its era');assert(w.ClassicsAtlas.getResults().every(id=>w.ATLAS_DATA.books.find(b=>b.id===id).start<=preset.year),'historical cutoff filters books');
 assert(d.querySelector('#legend').textContent.includes('modern book regions'));
 assert(d.querySelector('#colorSelect').disabled);
 assert.equal(d.querySelectorAll('.country-label').length,0,'modern labels hidden');
}
change('#mapPeriod','rome');click('#historyNotes');assert(d.querySelector('#historyDialog').open);
change('#historicalRegion',w.ATLAS_DATA.historical.presets.find(p=>p.id==='rome').features.find(f=>f.properties.name==='Roman Empire').id);
assert(d.querySelector('#historyContent h2').textContent==='Roman Empire');
assert(d.querySelector('#historyContent').textContent.includes('Approximate reconstruction'));
click('#booksNearMapDate');assert.equal(w.ClassicsAtlas.getState().from,-2500);assert.equal(w.ClassicsAtlas.getState().to,100);
assert.equal(w.ClassicsAtlas.getState().mapPeriod,'rome');assert(!d.querySelector('#historyDialog').open);
click('#resetBtn');search('Seneca');change('#countrySelect','FRA');assert.equal(w.ClassicsAtlas.getResults().length,0);
change('#geographySelect','associations');assert.equal(w.ClassicsAtlas.getResults().length,3);
change('#countrySelect','ESP');click('.book-title');assert(d.querySelector('#detailContent').textContent.includes('Corsica'));
click('[data-close="detailDialog"]');click('#resetBtn');assert.equal(d.querySelector('#searchInput').value,'');assert(d.querySelector('#searchReply').hidden);

const mappedIds=new Set(Object.values(w.AtlasCore.counts(w.ATLAS_DATA.books)).flat().map(b=>typeof b==='string'?b:b.id));
assert.equal(mappedIds.size,1479,'all works contribute to actual country counts');
assert(w.ATLAS_DATA.places.some(p=>p.id==='BMU'),'Bermuda has map coordinates');
change('#countrySelect','BMU');assert(w.ClassicsAtlas.getResults().length>0);assert(d.querySelector('#bookList').textContent.includes('Mary Prince'));click('#resetBtn');
change('#collectionSelect','China’s Four Great Classics');
assert.equal(w.ClassicsAtlas.getResults().length,8,'four novels with five retained Stone volumes');
assert(d.querySelector('#bookList').textContent.includes('Water Margin'));
assert(d.querySelector('#bookList').textContent.includes('Dream of the Red Chamber'));
assert.equal(w.AtlasCore.decode(w.AtlasCore.encode(w.ClassicsAtlas.getState())).collection,'China’s Four Great Classics');
click('#resetBtn');
for(const q of ['Dream of the Red Chamber','The Story of the Stone','Water Margin','Outlaws of the Marsh','Romance of the Three Kingdoms','Journey to the West','100 Years of Solitude']){
 search(q);assert(w.ClassicsAtlas.getResults().length>0,q);click('#resetBtn');
}
change('#collectionSelect','Murty Classical Library');
assert(w.ClassicsAtlas.getResults().length>=14);click('#resetBtn');
click('[data-era=ancient]');assert.equal(w.ClassicsAtlas.getState().mapPeriod,'late-antiquity');assert.equal(w.ClassicsAtlas.getState().to,500);click('[data-era=medieval]');assert.equal(w.ClassicsAtlas.getState().mapPeriod,'americas');assert.equal(w.ClassicsAtlas.getState().from,500);click('#resetBtn');
change('#mapPeriod','ottoman');assert.equal(d.querySelectorAll('.historical-points g').length,6);assert(!d.querySelector('[data-region="Watassid Morocco"]'));click('#resetBtn');
click('#editTime');assert(d.querySelector('#timeDialog').open);assert(d.querySelector('#timeDialog #timelineBrush'));
const brush=d.querySelector('#timelineBrush');brush.getBoundingClientRect=()=>({left:100,width:910});
const point=(type,year,id=1)=>{const e=new w.MouseEvent(type,{bubbles:true,clientX:100+(year+2500)/5,button:0});Object.defineProperty(e,'pointerId',{value:id});brush.dispatchEvent(e);};
const assertRange=(from,to)=>{assert.equal(w.ClassicsAtlas.getState().from,from);assert.equal(w.ClassicsAtlas.getState().to,to);};
point('pointerdown',50);point('pointermove',500);assert(d.querySelector('#dateRange').textContent.includes('50 AD — 500 AD'));assertRange(-2500,2050);point('pointerup',500);assertRange(50,500);
assert(w.ClassicsAtlas.getResults().every(id=>{const b=w.ATLAS_DATA.books.find(b=>b.id===id);return b.start<=500&&b.end>=50;}));
point('pointerdown',500);point('pointermove',50);point('pointerup',50);assertRange(50,500);
point('pointerdown',1600);point('pointerup',1600);assertRange(1500,1700);assert(!w.ClassicsAtlas.getState().includeUnknown);
point('pointerdown',-500);point('pointermove',-100);point('pointercancel',-100);assertRange(1500,1700);assert(d.querySelector('#dateRange').textContent.includes('1500 AD — 1700 AD'));
point('pointerdown',-500);point('pointermove',-100);brush.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));point('pointerup',-100);assertRange(1500,1700);
point('pointerdown',1600);point('pointermove',1000,2);point('pointerup',1000,2);point('pointerup',1600);assertRange(1500,1700);
brush.dispatchEvent(new w.KeyboardEvent('keydown',{key:'End',bubbles:true}));brush.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assertRange(1850,2050);
point('pointerdown',-2500);point('pointerup',-2500);assertRange(-2500,-2300);click('[data-close=timeDialog]');assert(!d.querySelector('#timeDialog').open);
click('#resetBtn');
search('The Memorial Feast');assert(d.querySelector('#bookList').textContent.includes('Story origins'));
click('[data-detail="128c93724417"]');assert(d.querySelector('#detailContent').textContent.includes('1922 AD – 1926 AD'));assert(d.querySelector('#detailContent').textContent.includes('1400 AD – 1800 AD'));
click('[data-origin-from="1400"]');assertRange(1400,1800);assert(!d.querySelector('#detailDialog').open);click('#resetBtn');
search('African Myths of Origin');click('[data-detail="5739e0183ff5"]');assert.equal(d.querySelectorAll('.origin-layers li').length,5);assert(d.querySelector('#detailContent').textContent.includes('Origin not securely dated'));click('[data-origin-from="-2400"]');assertRange(-2400,-500);click('#resetBtn');
assert(d.querySelector('#coverageLabel').textContent.includes('1479 dates / ranges'));
search('A Nation of Women');assert(d.querySelector('#bookList').textContent.includes('1911 AD'));
click('[data-detail="550f0836c359"]');assert(d.querySelector('#detailContent').textContent.includes('Mi opinión'));click('[data-close="detailDialog"]');
click('#resetBtn');search('A History of My Times');assert(d.querySelector('#bookList').textContent.includes('c. 362–350 BC'));
click('[data-detail="ad76f6ff8b40"]');assert(d.querySelector('#detailContent').textContent.includes('composition'));click('[data-close="detailDialog"]');click('#resetBtn');
search('ancient Greek poetry before the 4th century BC');assert(w.ClassicsAtlas.getResults().length>=2);assert(d.querySelector('#bookList').textContent.includes('The Iliad'));assert.equal(w.ClassicsAtlas.getState().mapPeriod,'greece');
click('#undoSearch');assert.equal(w.ClassicsAtlas.getResults().length,1479);
change('#countrySelect','TUR');assert(w.ClassicsAtlas.getResults().length>0);assert.equal(d.querySelector('#resultsTitle').textContent,'Turkey');
change('#countrySelect','ATA');assert.equal(w.ClassicsAtlas.getResults().length,0);assert(d.querySelector('.empty'));
click('#resetBtn');change('#traditionSelect','Japanese');assert(w.ClassicsAtlas.getResults().length>=2);
change('#colorSelect','category');assert(d.querySelector('#legend').textContent.includes('LEADING CATEGORY'));
click('#themeBtn');assert.equal(d.documentElement.dataset.theme,'dark');
change('#mapPeriod','rome');click('#globeBtn');assert(d.querySelector('.historical-region').getAttribute('d'));assert.equal(w.ClassicsAtlas.getState().projection,'globe');click('#flatBtn');change('#mapPeriod','modern');
const firstId=d.querySelector('.book-card').dataset.book;change(`[data-status="${firstId}"]`,'read');click(`[data-rate="${firstId}"][data-rating="4"]`);assert.equal(w.ClassicsAtlas.getShelf()[firstId].rating,4);
click('#shelfBtn');assert.equal(w.ClassicsAtlas.getResults().length,1);assert(d.body.classList.contains('shelf-view'));
click(`[data-detail="${firstId}"]`);assert(d.querySelector('#detailDialog').open);const selectedBook=w.ATLAS_DATA.books.find(b=>b.id===firstId);assert(d.querySelector('#detailContent').textContent.includes(selectedBook.pages?selectedBook.pages+' pages':'Unknown — edition not verified'));assert(d.querySelector('#detailContent').textContent.includes('Collection')); click('[data-close="detailDialog"]');
click('#shareBtn');assert(d.querySelector('#shareDialog').open);const share=d.querySelector('#shareText').value;assert(!share.includes(firstId));assert(!share.includes('rating'));click('[data-close="shareDialog"]');
const saved={};for(let i=0;i<w.localStorage.length;i++){const k=w.localStorage.key(i);saved[k]=w.localStorage.getItem(k);}dom.window.close();
dom=load(saved,true);w=dom.window;d=w.document;assert.equal(w.ClassicsAtlas.getShelf()[firstId].status,'read');assert.equal(w.ClassicsAtlas.getShelf()[firstId].rating,4);assert.equal(d.documentElement.dataset.theme,'dark');
assert(d.querySelector('#results').hidden,'mobile starts with the map exposed');assert(d.body.classList.contains('results-closed'));
assert(!d.querySelector('#filters').hidden,'mobile filters default open in a bounded section');change('#mapPeriod','greece');assert(d.querySelector('.historical-region'));d.querySelector('#bookPinsToggle').click();assert.equal(d.querySelectorAll('.marker').length,0);d.querySelector('#bookPinsToggle').click();assert(d.querySelectorAll('.marker').length>0);assert(d.querySelector('#filters').classList.contains('mobile-open'));click('#collapseFilters');assert(!d.querySelector('#filters').classList.contains('mobile-open'));
click('.mobile-views [data-view="timeline"]');assert.equal(w.ClassicsAtlas.getState().view,'timeline');assert(!d.querySelector('#timelineList').hidden);assert(d.querySelector('.timeline-group'));
click('.mobile-views [data-view="map"]');change('#fromNumber',-700);change('#toNumber',-400);assert.equal(w.ClassicsAtlas.getState().from,-700);assert.equal(w.ClassicsAtlas.getState().to,-400);assert(!w.ClassicsAtlas.getState().includeUnknown);
click('#resetBtn');click('#closeResults');assert(d.querySelector('#results').hidden);click('#openResults');assert(!d.querySelector('#results').hidden);click('#expandCollection');assert(d.body.classList.contains('collection-expanded'));click('#expandCollection');assert(!d.body.classList.contains('collection-expanded'));
click('#coverageBtn');assert(d.querySelector('#aboutDialog').open);click('[data-close="aboutDialog"]');
assert.equal(errors.length,0,errors.join('\n'));dom.window.close();console.log('UI event checks passed: initialization, real map paths, filters, search/undo, empty states, themes, globe, shelves, ratings, reload persistence, details, private sharing, mobile controls, timeline, and dialogs.');
