"""Reviewed source selections; unmatched works remain visible instead of disappearing."""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1]
books=json.loads((R/'data/catalog.json').read_text()); by={b['id']:b for b in books}
def item(title,ids=None,note='',extent='whole work'):
 return dict(title=title,bookIds=ids or [],note=note,extent=extent)
def path(id,title,curator,badge,region,description,source,items,scope):
 return dict(id=id,title=title,curator=curator,badge=badge,region=region,description=description,source=source,version='2026-09-21',scope=scope,items=[dict(x,id=f'{id}-{i+1}') for i,x in enumerate(items)])
P=[]
P.append(path('oxford-balliol','A first term of Greek classics','Balliol College, Oxford','Preparatory reading','Greece','Begin with a homecoming, then two very different visions of the Greek stage.','https://www.balliol.ox.ac.uk/admissions/undergraduate-admissions/classics-reading-lists',[
item('The Odyssey',['09921623539b'],'Read the whole poem in translation; Greek-language preparation additionally specifies books 9 and 12.'),
item('Bacchae',['c57816976d75'],'Read Bacchae, not the other plays in this volume. Greek preparation specifies lines 1–368.','component'),
item('Lysistrata',['708fc173225e'],'Read Lysistrata, not the entire collected edition. Greek preparation specifies lines 1–253.','component')], 'The three whole works assigned in translation before arrival in Balliol’s July 2026 guidance. This is a specific preparation sequence, not the Oxford degree or every Mods assignment.'))
P.append(path('eastern-classics','Eastern classics: an introduction','Classics Atlas · from St. John’s','Atlas selection','China · India · Japan','Follow a route through ethical questions, spiritual inquiry, and the literature of everyday life.','https://www.sjc.edu/academic-programs/graduate/masters-eastern-classics/reading-lists',[
item('Analects',['37e3f8924149'],'Short conversations reward slow reading; keep track of recurring ideas about conduct.'),item('Mencius',['f1a3697281a1'],'Compare the arguments about human nature with the Analects.'),item('The Book of Chuang Tzu',['d060b7f73b0f'],'Read the parables as challenges to familiar distinctions.'),item('Tao Te Ching',['f6df9652392a'],'Try a few chapters at a time and compare their language.'),item('The Bhagavad Gita',['2e7fdd1d1482'],'A dialogue about action and obligation within a much larger epic.','component'),item('The Lotus Sutra',[],'Catalog match pending; consult the program source.'),item('The Tale of the Heike',['5bc2b8a65668'],'Follow the changing fortunes of families and political power.'),item('The Pillow Book',['47116f264c6e'],'Read lists and observations alongside the longer narrative works.'),item('The Tale of Genji',['5d12c59b73dc'],'Allow a longer reading period and use the edition’s character guide.')], 'Nine Atlas-selected entry points from the published program. This shorter route is our adaptation; the college’s own public list is also selective.'))
P.append(path('middle-eastern','Epic, poetry and philosophy of the Middle East','Classics Atlas · from St. John’s','Atlas selection','Middle East','Move from epic journeys to questions of knowledge, community and spiritual life.','https://www.sjc.edu/academic-programs/graduate/master-arts-middle-eastern-classics/reading-lists',[
item('The Epic of Gilgamesh',['62b9b51109ff'],'Start with the central friendship and the search for a response to mortality.'),item('Shahnameh',['e5c99c209601'],'Use the genealogy and introduction to navigate a long epic.'),item('Rubaiyat',['c5e230253773'],'Notice the translator and the selection: English versions differ substantially.'),item('The Conference of the Birds',['7fff2ff67581'],'Follow the frame journey and the stories embedded within it.'),item('Hayy ibn Yaqzan',[],'Catalog match pending.'),item('The Muqaddimah',[],'Catalog match pending.')], 'Six Atlas-selected entry points, not the complete graduate program. Unmatched works are retained for future catalog expansion.'))
P.append(path('harvard-ancient','Ancient masterpieces, across cultures','Harvard · public course outline','Course outline','World','Travel between foundational stories and the audiences that gave them new lives.','https://pll.harvard.edu/course/ancient-masterpieces-world-literature',[
item('Introduction: Goethe and world literature',[],'Introductory topic; the public outline does not identify a specific assigned Goethe text.','topic'),item('The Epic of Gilgamesh',['62b9b51109ff']),item('The Odyssey',['09921623539b']),item('The 1001 Nights',['1feea7ebc200']),item('The Tale of Genji',['5d12c59b73dc']),item('The Lusiads',['cabc9f64af16'])], 'All six topics in the published outline. Exact assigned passages are not specified; progress records a topic, not completion of the entire featured book.'))
for i in P[-1]['items']:i['extent']='topic'
P.append(path('harvard-chinax','Five views of modern China','Harvard · David Wang','Course selection','China','Five authors provide different ways into modern Chinese life and literary expression.','https://pll.harvard.edu/course/chinax-book-club-five-authors-five-books-five-views-china',[
item('China in Ten Words',[],'Yu Hua · ISBN 9780307739797. Catalog match pending.'),item('Red Sorghum',[],'Mo Yan · ISBN 9780140168549. Catalog match pending.'),item("Lenin’s Kisses",[],'Yan Lianke · ISBN 9780802121776. Catalog match pending.'),item('Waiting',[],'Ha Jin · ISBN 9780375706417. Catalog match pending.'),item('The Song of Everlasting Sorrow',[],'Wang Anyi · ISBN 9780231143431. Catalog match pending.')], 'All five featured books. The Harvard course page marks this course archived/closed. This is not the Harvard East Asian Studies degree.'))
ranges=['Part I: front matter and chapters 1–10','Part I: chapters 11–20','Part I: chapters 21–26','Part I: chapters 27–35','Part I: chapters 36–52','Part II: introduction, front matter and chapters 1–11','Part II: chapters 12–21','Part II: chapters 22–35','Part II: chapters 36–53','Part II: chapters 54–70','Part II: chapters 71–74']
P.append(path('yale-quixote','Read Don Quixote with Yale','Yale · Roberto González Echevarría','Course syllabus','Spain','A chapter-by-chapter companion to an extraordinary journey, with the original lectures one click away.','https://oyc.yale.edu/spanish-and-portuguese/span-300',[
*[item(x,['a57ba14e6a7f'],'Chapter groups follow the published sessions; use the source for lectures and original assignments.','excerpt') for x in ranges],item('Four Exemplary Stories',[],'Supplementary reading; consult the original course for the assigned stories.','excerpt'),item("Cervantes’ Don Quixote: A Casebook",[],'Secondary reading; edited by Roberto González Echevarría.','resource'),item('Imperial Spain, 1469–1716',[],'Secondary reading; J. H. Elliott.','resource')], 'Fall 2009 course. Repeated lecture sessions are grouped into reading units; all three supplementary readings are retained. Source specifies John Rutherford’s Don Quixote translation.'))
P.append(path('latin-american','Five routes into Latin American literature','John King · Five Books','Expert selection','Latin America','A compact selection that moves between labyrinths, family histories and lives at the margins.','https://fivebooks.com/best-books/latin-american-novels-john-king/',[
item('Labyrinths',[],'Jorge Luis Borges. Catalog match pending.'),item('One Hundred Years of Solitude',['world-fada12986ba1'],'Keep a family tree nearby; repeated names are part of the experience.'),item('Conversation in the Cathedral',[],'Mario Vargas Llosa. Catalog match pending.'),item('The Hour of the Star',['1110b16a09cc'],'A short work that invites questions about who gets to tell another person’s story.'),item('2666',[],'Roberto Bolaño. Catalog match pending.')], 'The five works selected by John King for Five Books. Reading notes are original Atlas guidance; the interview is linked, not reproduced.'))
P.append(path('african-novels','African novels that stay with you','Blessing Musariri · Five Books','Expert selection','Africa', 'A writer’s personal selection, including an anthology of women’s writing.','https://fivebooks.com/category/world/africa/',[
item('The Famished Road',[],'Ben Okri. Catalog match pending.'),item('The Memory of Love',[],'Aminatta Forna. Catalog match pending.'),item('Burma Boy',[],'Biyi Bandele. Catalog match pending.'),item('Half of a Yellow Sun',[],'Chimamanda Ngozi Adichie. Catalog match pending.'),item('Opening Spaces',[],'Yvonne Vera, editor. An anthology of contemporary African women’s writing; catalog match pending.')], 'All five selections listed for Blessing Musariri in the Five Books Africa directory. A personal selection, not a comprehensive African canon.'))
P.append(path('china-four','China’s four great novels','Classics Atlas','Atlas original','China','Four ambitious novels, with enough room to follow each at your own pace.','https://en.wikipedia.org/wiki/Classic_Chinese_Novels',[
item('Romance of the Three Kingdoms',['1ed729c458f3'],'Check whether your edition is complete or abridged.'),item('Water Margin',['world-087cdb477866'],'Keep track of the growing cast; consult the introduction about versions.'),item('Journey to the West',['8d06d5c3ac44'],'This catalog edition is an abridgment. Completing it does not mean reading the full novel.','abridgment'),item('Dream of the Red Chamber',['fc985c45e23b','61f2b304edbe','0570787dde7c','403fb8ce4de7','1d7ecebde0ea'],'The catalog presents the work in five volumes; choose the volume you are reading.')], 'An Atlas sequence. Editions and abridgments are explicit, and the five Dream of the Red Chamber volumes remain separate shelf records.'))
P.append(path('small-beginnings','Start small: ideas that travel','Classics Atlas','Atlas original','World','Three works suited to reading in small passages, with time left for reflection.','',[
item('Tao Te Ching',['f6df9652392a'],'Choose a few chapters; note an image or question to revisit.'),item('The Analects',['37e3f8924149'],'Compare passages about learning, friendship and conduct.'),item('Meditations',['440be2c9b8e7'],'Treat the entries as private exercises rather than a single continuous argument.')], 'Original Atlas curation; “small” refers to passage-based reading, not a verified page-count limit.'))
# Curated book-level guidance derives from our path annotations, never from invented ratings.
guidance={}
for p in P:
 for i in p['items']:
  for bid in i['bookIds']:
   assert bid in by,(p['id'],bid)
   if i['note'] and bid not in guidance:guidance[bid]={'startHere':i['note'],'whyRead':p['description'],'source':p['source'],'label':'Atlas reading guidance'}
(R/'data/reading-paths.json').write_text(json.dumps(P,ensure_ascii=False,indent=2))
(R/'data/reading-guidance.json').write_text(json.dumps(guidance,ensure_ascii=False,indent=2))
print(len(P),'paths;',sum(len(p['items']) for p in P),'assignments; unresolved entries retained')
